# Activate with: --spring.profiles.active=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/minierp
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.h2.console.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
